-- ============================================================
-- ESQUEMA COMPLETO SUPABASE POSTGRESQL — DASHBOARD COMERCIAL CNPJ SP
-- Cole este script no SQL Editor do Supabase (https://supabase.com)
-- ============================================================

-- 1. TABELA UNIFICADA DE EMPRESAS (Todas as cidades em uma unica estrutura)
CREATE TABLE IF NOT EXISTS public.empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj VARCHAR(14) NOT NULL UNIQUE,
    razao_social TEXT NOT NULL,
    nome_fantasia TEXT,
    uf VARCHAR(2) DEFAULT 'SP',
    cidade TEXT NOT NULL,
    bairro TEXT,
    telefone TEXT,
    whatsapp TEXT,
    msg_whatsapp TEXT,
    site TEXT,
    email TEXT,
    cnae VARCHAR(10),
    segmento TEXT,
    porte VARCHAR(20) DEFAULT 'MEI / ME',
    capital_social NUMERIC(15,2) DEFAULT 0.00,
    ativa BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- INDICES DE ALTA PERFORMANCE (< 10ms por consulta)
CREATE INDEX IF NOT EXISTS idx_empresas_cidade ON public.empresas (cidade);
CREATE INDEX IF NOT EXISTS idx_empresas_cnae ON public.empresas (cnae);
CREATE INDEX IF NOT EXISTS idx_empresas_porte ON public.empresas (porte);
CREATE INDEX IF NOT EXISTS idx_empresas_whatsapp ON public.empresas (whatsapp) WHERE whatsapp IS NOT NULL AND whatsapp != '';
CREATE INDEX IF NOT EXISTS idx_empresas_site ON public.empresas (site) WHERE site IS NOT NULL AND site != '';

-- 2. TABELA DE VENDEDORES / USUARIOS (Complemento ao Supabase Auth)
CREATE TABLE IF NOT EXISTS public.vendedores (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    nome_completo TEXT NOT NULL,
    cargo TEXT DEFAULT 'Consultor Comercial',
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. TABELA DE MINHAS LISTAS (Prospecção Salva por Vendedor)
CREATE TABLE IF NOT EXISTS public.minhas_listas (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    vendedor_id UUID REFERENCES auth.users ON DELETE CASCADE,
    vendedor_email TEXT NOT NULL,
    nome_lista TEXT NOT NULL,
    total_empresas INT DEFAULT 0,
    filtros_utilizados JSONB DEFAULT '{}'::jsonb,
    empresas_data JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

CREATE INDEX IF NOT EXISTS idx_minhas_listas_vendedor ON public.minhas_listas (vendedor_id);

-- 4. SEGURANÇA E POLÍTICAS DE ACESSO (Row Level Security - RLS)
ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.minhas_listas ENABLE ROW LEVEL SECURITY;

-- Leitura publica permitida para a tabela de empresas
CREATE POLICY "Leitura empresas autorizada"
    ON public.empresas FOR SELECT
    USING (true);

-- Permissoes da tabela de vendedores
CREATE POLICY "Vendedores podem ver seu proprio perfil"
    ON public.vendedores FOR SELECT
    USING (auth.uid() = id);

-- Permissoes das listas salvas (Cada vendedor ve apenas as suas listas)
CREATE POLICY "Vendedor gerencia apenas suas listas"
    ON public.minhas_listas FOR ALL
    USING (auth.uid() = vendedor_id OR vendedor_email = auth.email());
